var GOOGIE_CUR_LANG=null,GOOGIE_DEFAULT_LANG="en";
function GoogieSpell(a,b){var c;c=getCookie("language");GOOGIE_CUR_LANG=c!=null?c:GOOGIE_DEFAULT_LANG;this.img_dir=a;this.server_url=b;this.lang_to_word=this.org_lang_to_word={da:"Dansk",de:"Deutsch",en:"English",es:"Espa&#241;ol",fr:"Fran&#231;ais",it:"Italiano",nl:"Nederlands",pl:"Polski",pt:"Portugu&#234;s",fi:"Suomi",sv:"Svenska"};this.langlist_codes=AJS.keys(this.lang_to_word);this.show_change_lang_pic=!0;this.change_lang_pic_placement="left";this.report_state_change=!0;this.el_scroll_top=this.ta_scroll_top=
0;this.lang_chck_spell="";this.lang_revert="Revert to";this.lang_close="Close";this.lang_rsm_edt='<A TITLE="Close spellcheck mode, return to editing">Edit</A>';this.lang_no_error_found="No spelling errors found";this.lang_no_suggestions="No suggestions";this.report_ta_not_found=this.edit_layer_dbl_click=this.use_close_btn=this.decoration=this.show_spell_img=!0;this.custom_no_spelling_error=this.custom_ajax_error=null;this.custom_menu_builder=[];this.custom_item_evaulator=null;this.extra_menu_items=
[];this.custom_spellcheck_starter=null;this.main_controller=!0;this.all_errors_fixed_observer=this.show_menu_observer=this.spelling_state_observer=this.lang_state_observer=null;this.use_focus=!1;this.focus_link_b=this.focus_link_t=null;this.cnt_errors_fixed=this.cnt_errors=0;AJS.AEV(document,"click",AJS.$b(function(a){a=AJS.getEventElm(a);a.googie_action_btn!="1"&&this.isLangWindowShown()&&this.hideLangWindow();a.googie_action_btn!="1"&&this.isErrorWindowShown()&&this.hideErrorWindow()},this))}
GoogieSpell.prototype.decorateTextarea=function(a){this.text_area=typeof a=="string"?AJS.$(a):a;var b;if(this.text_area!=null){if(!AJS.isDefined(this.spell_container)&&this.decoration){var c=AJS.TABLE(),d=AJS.TBODY(),e=AJS.TR(),a=AJS.isDefined(this.force_width)?this.force_width:this.text_area.offsetWidth+"px";b=AJS.isDefined(this.force_height)?this.force_height:"";var g=AJS.TD();this.spell_container=g;e.appendChild(g);d.appendChild(e);c.appendChild(d);AJS.insertBefore(c,this.text_area);AJS.setHeight(c,
g,b);AJS.setWidth(c,g,a);g.style.textAlign="right"}this.checkSpellingState()}else this.report_ta_not_found&&alert("Text area not found")};GoogieSpell.prototype.setSpellContainer=function(a){this.spell_container=AJS.$(a)};GoogieSpell.prototype.setLanguages=function(a){this.lang_to_word=a;this.langlist_codes=AJS.keys(a)};GoogieSpell.prototype.setForceWidthHeight=function(a,b){this.force_width=a;this.force_height=b};GoogieSpell.prototype.setDecoration=function(a){this.decoration=a};
GoogieSpell.prototype.dontUseCloseButtons=function(){this.use_close_btn=!1};GoogieSpell.prototype.appendNewMenuItem=function(a,b,c){this.extra_menu_items.push([a,b,c])};GoogieSpell.prototype.appendCustomMenuBuilder=function(a,b){this.custom_menu_builder.push([a,b])};GoogieSpell.prototype.setFocus=function(){try{return this.focus_link_b.focus(),this.focus_link_t.focus(),!0}catch(a){return!1}};GoogieSpell.prototype.getValue=function(a){return a.value};
GoogieSpell.prototype.setValue=function(a,b){a.value=b};GoogieSpell.prototype.setStateChanged=function(a){this.state=a;this.spelling_state_observer!=null&&this.report_state_change&&this.spelling_state_observer(a,this)};GoogieSpell.prototype.setReportStateChange=function(a){this.report_state_change=a};GoogieSpell.prototype.getGoogleUrl=function(){return this.server_url+GOOGIE_CUR_LANG};GoogieSpell.escapeSepcial=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")};
GoogieSpell.createXMLReq=function(a){return'<?xml version="1.0" encoding="utf-8" ?><spellrequest textalreadyclipped="0" ignoredups="0" ignoredigits="1" ignoreallcaps="1"><text>'+a+"</text></spellrequest>"};
GoogieSpell.prototype.spellCheck=function(a){var b=this;this.cnt_errors=this.cnt_errors_fixed=0;this.setStateChanged("checking_spell");this.main_controller&&this.appendIndicator(this.spell_span);this.error_links=[];this.ta_scroll_top=this.text_area.scrollTop;try{this.hideLangWindow()}catch(c){}this.ignore=a;if(this.getValue(this.text_area)==""||a)b.custom_no_spelling_error?b.custom_no_spelling_error(b):b.flashNoSpellingErrorState(),b.removeIndicator();else{this.createEditLayer(this.text_area.offsetWidth,
this.text_area.offsetHeight);this.createErrorWindow();AJS.getBody().appendChild(this.error_window);try{netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead")}catch(d){}if(this.main_controller)this.spell_span.onclick=null;this.orginal_text=this.getValue(this.text_area);var a=AJS.getRequest(this.getGoogleUrl()),e;a.addCallback(function(a){b.results=b.parseResult(a);a.match(/<c.*>/)!=null?(b.showErrorsInIframe(),b.resumeEditingState()):b.custom_no_spelling_error?b.custom_no_spelling_error(b):
b.flashNoSpellingErrorState();b.removeIndicator()});e=null;a.addErrback(function(a,c){b.custom_ajax_error?b.custom_ajax_error(c):alert("An error was encountered on the server. Please try again later.");b.main_controller&&(AJS.removeElement(b.spell_span),b.removeIndicator());b.checkSpellingState()});e=null;e=GoogieSpell.escapeSepcial(this.orginal_text);a.sendReq(GoogieSpell.createXMLReq(e))}};
GoogieSpell.prototype.parseResult=function(a){var b=/\w+="(\d+|true)"/g,c=/\t/g,a=a.match(/<c[^>]*>[^<]*<\/c>/g),d=[];if(a==null)return d;for(var e=0;e<a.length;e++){var g=[];this.errorFound();g.attrs=[];for(var f=a[e].match(b),h=0;h<f.length;h++){var k=f[h].split(/=/),j=k[1].replace(/"/g,"");g.attrs[k[0]]=j!="true"?parseInt(j):j}g.suggestions=[];f=a[e].replace(/<[^>]*>/g,"").split(c);for(h=0;h<f.length;h++)f[h]!=""&&g.suggestions.push(f[h]);d.push(g)}return d};
GoogieSpell.prototype.errorFixed=function(){this.cnt_errors_fixed++;this.all_errors_fixed_observer&&this.cnt_errors_fixed==this.cnt_errors&&(this.hideErrorWindow(),this.all_errors_fixed_observer())};GoogieSpell.prototype.errorFound=function(){this.cnt_errors++};GoogieSpell.prototype.createErrorWindow=function(){this.error_window=AJS.DIV();this.error_window.className="googie_window";this.error_window.googie_action_btn="1"};
GoogieSpell.prototype.isErrorWindowShown=function(){return this.error_window!=null&&this.error_window.style.visibility=="visible"};GoogieSpell.prototype.hideErrorWindow=function(){try{if(this.error_window.style.visibility="hidden",this.error_window_iframe)this.error_window_iframe.style.visibility="hidden"}catch(a){}};
GoogieSpell.prototype.updateOrginalText=function(a,b,c,d){var e=this.orginal_text.substring(0,a),a=this.orginal_text.substring(a+b.length);this.orginal_text=e+c+a;this.setValue(this.text_area,this.orginal_text);b=c.length-b.length;for(c=0;c<this.results.length;c++)c!=d&&c>d&&(this.results[c].attrs.o+=b)};GoogieSpell.prototype.saveOldValue=function(a,b){a.is_changed=!0;a.old_value=b};
GoogieSpell.prototype.createListSeparator=function(){var a=AJS.TD(" ");a.googie_action_btn="1";a.style.cursor="default";a.style.fontSize="3px";a.style.borderTop="1px solid #ccc";a.style.paddingTop="3px";return AJS.TR(a)};
GoogieSpell.prototype.correctError=function(a,b,c,d){var e=b.innerHTML,c=c.innerHTML,g=this.results[a].attrs.o;if(d)d=b.previousSibling.innerHTML,b.previousSibling.innerHTML=d.slice(0,d.length-1),e=" "+e,g--;this.hideErrorWindow();this.updateOrginalText(g,e,c,a);b.innerHTML=c;b.style.color="green";b.is_corrected=!0;this.results[a].attrs.l=c.length;AJS.isDefined(b.old_value)||this.saveOldValue(b,e);this.errorFixed()};
GoogieSpell.prototype.showErrorWindow=function(a,b){this.show_menu_observer&&this.show_menu_observer(this);var c=this,d=AJS.absolutePosition(a);d.y-=this.edit_layer.scrollTop;this.error_window.style.visibility="visible";AJS.setTop(this.error_window,d.y+20);AJS.setLeft(this.error_window,d.x);this.error_window.innerHTML="";d=AJS.TABLE({"class":"googie_list"});d.googie_action_btn="1";var e=AJS.TBODY(),g=!1;if(this.custom_menu_builder!=[])for(var f=0;f<this.custom_menu_builder.length;f++){var h=this.custom_menu_builder[f];
if(h[0](this.results[b])){g=h[1](this,e,a);break}}if(!g){var g=this.results[b].suggestions,k=this.results[b].attrs.o;if(g.length==0){var f=AJS.TR(),h=AJS.TD({style:"cursor: default;"}),j=AJS.SPAN();j.innerHTML=this.lang_no_suggestions;AJS.ACN(h,AJS.TN(j.innerHTML));h.googie_action_btn="1";f.appendChild(h);e.appendChild(f)}for(i=0;i<g.length;i++)f=AJS.TR(),h=AJS.TD(),j=AJS.SPAN(),j.innerHTML=g[i],h.appendChild(AJS.TN(j.innerHTML)),j=function(c){c=AJS.getEventElm(c);this.correctError(b,a,c)},AJS.AEV(h,
"click",AJS.$b(j,this)),h.onmouseover=GoogieSpell.item_onmouseover,h.onmouseout=GoogieSpell.item_onmouseout,f.appendChild(h),e.appendChild(f);if(a.is_changed&&a.innerHTML!=a.old_value){var m=a.old_value,g=AJS.TR(),f=AJS.TD();f.onmouseover=GoogieSpell.item_onmouseover;f.onmouseout=GoogieSpell.item_onmouseout;h=AJS.SPAN({"class":"googie_list_revert"});h.innerHTML=this.lang_revert+" "+m;f.appendChild(h);AJS.AEV(f,"click",AJS.$b(function(){this.updateOrginalText(k,a.innerHTML,m,b);a.is_corrected=!0;a.style.color=
"#b91414";a.innerHTML=m;this.hideErrorWindow()},this));g.appendChild(f);e.appendChild(g)}var g=AJS.TR(),f=AJS.TD({style:"cursor: default"}),l=AJS.INPUT({style:"width: 120px; margin:0; padding:0",value:a.innerHTML});l.googie_action_btn="1";var h=AJS.$b(function(){if(l.value!="")AJS.isDefined(a.old_value)||this.saveOldValue(a,a.innerHTML),this.updateOrginalText(k,a.innerHTML,l.value,b),a.style.color="green",a.is_corrected=!0,a.innerHTML=l.value,this.hideErrorWindow();return!1},this),j=AJS.IMG({src:this.img_dir+
"ok.gif",style:"width: 32px; height: 16px; margin-left: 2px; margin-right: 2px; cursor: pointer;"}),n=AJS.FORM({style:"margin: 0; padding: 0; cursor: default;"},l,j);n.googie_action_btn="1";f.googie_action_btn="1";AJS.AEV(n,"submit",h);AJS.AEV(j,"click",h);f.appendChild(n);g.appendChild(f);e.appendChild(g);this.extra_menu_items.length>0&&AJS.ACN(e,this.createListSeparator());var o=function(b){if(b<c.extra_menu_items.length){var d=c.extra_menu_items[b];if(!d[2]||d[2](a,c)){var g=AJS.TR(),f=AJS.TD(d[0]);
f.onmouseover=GoogieSpell.item_onmouseover;f.onmouseout=GoogieSpell.item_onmouseout;AJS.AEV(f,"click",function(){return d[1](a,c)});AJS.ACN(g,f);AJS.ACN(e,g)}o(b+1)}};o(0);o=null;this.use_close_btn&&AJS.ACN(e,this.createCloseButton(this.hideErrorWindow))}d.appendChild(e);this.error_window.appendChild(d);if(AJS.isIe()&&!this.error_window_iframe)d=AJS.IFRAME({style:"position: absolute; z-index: 0;"}),AJS.ACN(AJS.getBody(),d),this.error_window_iframe=d;if(AJS.isIe())d=this.error_window_iframe,AJS.setTop(d,
this.error_window.offsetTop),AJS.setLeft(d,this.error_window.offsetLeft),AJS.setWidth(d,this.error_window.offsetWidth),AJS.setHeight(d,this.error_window.offsetHeight),d.style.visibility="visible";d=this.createFocusLink("link");e.appendChild(AJS.TR(AJS.TD({style:"text-align: right; font-size: 1px; height: 1px; margin: 0; padding: 0;"},d)));d.focus()};
GoogieSpell.prototype.createEditLayer=function(a,b){this.edit_layer=AJS.DIV({"class":"googie_edit_layer"});this.edit_layer.className=this.text_area.className;this.edit_layer.style.border="1px solid #999";this.edit_layer.style.backgroundColor="#f7f7f7";this.edit_layer.style.padding="3px";this.edit_layer.style.margin="0px";AJS.setWidth(this.edit_layer,a-8);AJS.nodeName(this.text_area)!="input"||this.getValue(this.text_area)==""?(this.edit_layer.style.overflow="auto",AJS.setHeight(this.edit_layer,b-
6)):this.edit_layer.style.overflow="hidden";if(this.edit_layer_dbl_click){var c=this,d;this.edit_layer.ondblclick=function(a){if(AJS.getEventElm(a).className!="googie_link"&&!c.isErrorWindowShown()){c.resumeEditing();var b=function(){c.text_area.focus();b=null};AJS.callLater(b,10)}return!1};d=null}};
GoogieSpell.prototype.resumeEditing=function(){this.setStateChanged("spell_check");this.switch_lan_pic.style.display="inline";if(this.edit_layer)this.el_scroll_top=this.edit_layer.scrollTop;this.hideErrorWindow();if(this.main_controller)this.spell_span.className="googie_no_style";if(!this.ignore){try{this.edit_layer.parentNode.removeChild(this.edit_layer),this.use_focus&&(AJS.removeElement(this.focus_link_t),AJS.removeElement(this.focus_link_b))}catch(a){}AJS.showElement(this.text_area);if(this.el_scroll_top!=
void 0)this.text_area.scrollTop=this.el_scroll_top}this.checkSpellingState(!1)};GoogieSpell.prototype.createErrorLink=function(a,b){var c=AJS.SPAN({"class":"googie_link"}),d=this,e=function(){d.showErrorWindow(c,b);e=null;return!1};AJS.AEV(c,"click",e);c.googie_action_btn="1";c.g_id=b;c.is_corrected=!1;c.oncontextmenu=e;c.innerHTML=a;return c};
GoogieSpell.createPart=function(a){if(a==" ")return AJS.TN(" ");AJS.SPAN();navigator.userAgent.toLowerCase().indexOf("safari");var b=AJS.SPAN(),a=GoogieSpell.escapeSepcial(a),a=a.replace(/\n/g,"<br>"),a=a.replace(/    /g," &nbsp;"),a=a.replace(/^ /g,"&nbsp;"),a=a.replace(/ $/g,"&nbsp;");b.innerHTML=a;return b};
GoogieSpell.prototype.showErrorsInIframe=function(){var a=AJS.DIV();a.style.textAlign="left";var b=0,c=this.results;if(c.length>0){for(var d=0;d<c.length;d++){var e=c[d].attrs.o,g=c[d].attrs.l,f=this.orginal_text.substring(b,e),f=GoogieSpell.createPart(f);a.appendChild(f);b+=e-b;e=this.createErrorLink(this.orginal_text.substr(e,g),d);this.error_links.push(e);a.appendChild(e);b+=g}b=this.orginal_text.substr(b,this.orginal_text.length);b=GoogieSpell.createPart(b);a.appendChild(b)}else a.innerHTML=this.orginal_text;
var h=this;this.custom_item_evaulator&&AJS.map(this.error_links,function(a){h.custom_item_evaulator(h,a)});AJS.ACN(this.edit_layer,a);this.text_area_bottom=this.text_area.offsetTop+this.text_area.offsetHeight;AJS.hideElement(this.text_area);AJS.insertBefore(this.edit_layer,this.text_area);if(this.use_focus)this.focus_link_t=this.createFocusLink("focus_t"),this.focus_link_b=this.createFocusLink("focus_b"),AJS.insertBefore(this.focus_link_t,this.edit_layer),AJS.insertAfter(this.focus_link_b,this.edit_layer);
this.edit_layer.scrollTop=this.ta_scroll_top};
GoogieSpell.prototype.createLangWindow=function(){this.language_window=AJS.DIV({"class":"googie_window"});AJS.setWidth(this.language_window,100);this.language_window.googie_action_btn="1";var a=AJS.TABLE({"class":"googie_list"});AJS.setWidth(a,"100%");var b=AJS.TBODY();this.lang_elms=[];for(i=0;i<this.langlist_codes.length;i++){var c=AJS.TR(),d=AJS.TD();d.googieId=this.langlist_codes[i];this.lang_elms.push(d);var e=AJS.SPAN();e.innerHTML=this.lang_to_word[this.langlist_codes[i]];d.appendChild(AJS.TN(e.innerHTML));
AJS.AEV(d,"click",AJS.$b(function(a){a=AJS.getEventElm(a);this.deHighlightCurSel();this.setCurrentLanguage(a.googieId);this.lang_state_observer!=null&&this.lang_state_observer();this.highlightCurSel();this.hideLangWindow()},this));d.onmouseover=function(a){a=AJS.getEventElm(a);if(a.className!="googie_list_selected")a.className="googie_list_onhover"};d.onmouseout=function(a){a=AJS.getEventElm(a);if(a.className!="googie_list_selected")a.className="googie_list_onout"};c.appendChild(d);b.appendChild(c)}this.use_close_btn&&
b.appendChild(this.createCloseButton(this.hideLangWindow));this.highlightCurSel();a.appendChild(b);this.language_window.appendChild(a)};GoogieSpell.prototype.setCurrentLanguage=function(a){GOOGIE_CUR_LANG=a;var b=new Date;b.setTime(b.getTime()+31536E6);setCookie("language",a,b)};GoogieSpell.prototype.isLangWindowShown=function(){return this.language_window!=null&&this.language_window.style.visibility=="visible"};
GoogieSpell.prototype.hideLangWindow=function(){try{this.language_window.style.visibility="hidden",this.switch_lan_pic.className="googie_lang_3d_on"}catch(a){}};GoogieSpell.prototype.deHighlightCurSel=function(){this.lang_cur_elm.className="googie_list_onout"};
GoogieSpell.prototype.highlightCurSel=function(){GOOGIE_CUR_LANG==null&&(GOOGIE_CUR_LANG=GOOGIE_DEFAULT_LANG);for(var a=0;a<this.lang_elms.length;a++)this.lang_elms[a].googieId==GOOGIE_CUR_LANG?(this.lang_elms[a].className="googie_list_selected",this.lang_cur_elm=this.lang_elms[a]):this.lang_elms[a].className="googie_list_onout"};
GoogieSpell.prototype.showLangWindow=function(a,b,c){this.show_menu_observer&&this.show_menu_observer(this);AJS.isDefined(b)||(b=20);AJS.isDefined(c)||(c=100);this.createLangWindow();AJS.getBody().appendChild(this.language_window);a=AJS.absolutePosition(a);AJS.showElement(this.language_window);AJS.setTop(this.language_window,a.y+b);AJS.setLeft(this.language_window,a.x+c-this.language_window.offsetWidth);this.highlightCurSel();this.language_window.style.visibility="visible"};
GoogieSpell.prototype.createChangeLangPic=function(){var a=AJS.IMG({src:this.img_dir+"change_lang.gif",alt:"Change language"});a.googie_action_btn="1";var b=AJS.SPAN({"class":"googie_lang_3d_on",style:"padding-left: 6px;"},a);AJS.AEV(b,"click",AJS.$b(function(a){a=AJS.getEventElm(a);if(AJS.nodeName(a)=="img")a=a.parentNode;a.className=="googie_lang_3d_click"?(a.className="googie_lang_3d_on",this.hideLangWindow()):(a.className="googie_lang_3d_click",this.showLangWindow(b))},this));return b};
GoogieSpell.prototype.createSpellDiv=function(){var a=AJS.SPAN({"class":"googie_check_spelling_link"});a.innerHTML=this.lang_chck_spell;var b=null;this.show_spell_img&&(b=AJS.IMG({src:this.img_dir+"spellc.gif"}));return AJS.SPAN(b," ",a)};
GoogieSpell.prototype.flashNoSpellingErrorState=function(a){var b;b=a?function(){a();this.checkSpellingState()}:this.checkSpellingState;this.setStateChanged("no_error_found");if(this.main_controller){AJS.hideElement(this.switch_lan_pic);var c=AJS.IMG({src:this.img_dir+"blank.gif",style:"height: 16px; width: 1px;"}),d=AJS.SPAN();d.innerHTML=this.lang_no_error_found;AJS.RCN(this.spell_span,AJS.SPAN(c,d));this.spell_span.className="googie_check_spelling_ok";this.spell_span.style.textDecoration="none";
this.spell_span.style.cursor="default";AJS.callLater(AJS.$b(b,this),1200,[!1])}};
GoogieSpell.prototype.resumeEditingState=function(){this.setStateChanged("resume_editing");if(this.main_controller){AJS.hideElement(this.switch_lan_pic);var a=AJS.IMG({src:this.img_dir+"blank.gif",style:"height: 16px; width: 1px;"}),b=AJS.SPAN();b.innerHTML=this.lang_rsm_edt;AJS.RCN(this.spell_span,AJS.SPAN(a,b));this.spell_span.onclick=AJS.$b(function(){this.resumeEditing()},this);this.spell_span.className="googie_resume_editing"}try{this.edit_layer.scrollTop=this.ta_scroll_top}catch(c){}};
GoogieSpell.prototype.checkSpellingState=function(a){(!AJS.isDefined(a)||a)&&this.setStateChanged("spell_check");this.switch_lan_pic=this.show_change_lang_pic?this.createChangeLangPic():AJS.SPAN();a=this.createSpellDiv();a.onclick=this.custom_spellcheck_starter?this.custom_spellcheck_starter:AJS.$b(function(){this.spellCheck()},this);this.spell_span=a;this.main_controller&&(this.change_lang_pic_placement=="left"?AJS.RCN(this.spell_container,a," ",this.switch_lan_pic):AJS.RCN(this.spell_container,
this.switch_lan_pic," ",a))};GoogieSpell.item_onmouseover=function(a){a=AJS.getEventElm(a);a.className!="googie_list_revert"&&a.className!="googie_list_close"?a.className="googie_list_onhover":a.parentNode.className="googie_list_onhover"};GoogieSpell.item_onmouseout=function(a){a=AJS.getEventElm(a);a.className!="googie_list_revert"&&a.className!="googie_list_close"?a.className="googie_list_onout":a.parentNode.className="googie_list_onout"};
GoogieSpell.prototype.createCloseButton=function(a){return this.createButton(this.lang_close,"googie_list_close",AJS.$b(a,this))};GoogieSpell.prototype.createButton=function(a,b,c){var d=AJS.TR(),e=AJS.TD();e.onmouseover=GoogieSpell.item_onmouseover;e.onmouseout=GoogieSpell.item_onmouseout;b!=""?(b=AJS.SPAN({"class":b}),b.innerHTML=a):b=AJS.TN(a);e.appendChild(b);AJS.AEV(e,"click",c);d.appendChild(e);return d};GoogieSpell.prototype.removeIndicator=function(){try{AJS.removeElement(this.indicator)}catch(a){}};
GoogieSpell.prototype.appendIndicator=function(a){var b=AJS.IMG({src:this.img_dir+"indicator.gif",style:"margin-right: 5px;"});AJS.setWidth(b,16);AJS.setHeight(b,16);this.indicator=b;b.style.textDecoration="none";try{AJS.insertBefore(b,a)}catch(c){}};GoogieSpell.prototype.createFocusLink=function(a){return AJS.A({href:"javascript:;",name:a})};